### ISSUE TITLE
Logo Design For RenderLab

### ISSUE THREAD

**Issue by zularizal** [Ubpa/RenderLab#1]
Hi @Ubpa , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by Ubpa** [comment]
Feel free to design.
Thanks for your contibution :)

**Comment by zularizal** [comment]
Hi @Ubpa , here are some design logos for your project. Which one do you like?
If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57897903-07e3e180-7881-11e9-94c4-947941131746.png)

**Comment by Ubpa** [comment]
the 3rd one is great 👍

Could you design more logos like it with different
- color: simple, bright, soft
- amount of quads: 2 ( add some shadow like your profile picture), 3, 4
- orientation (the current one is good enough)

thanks

**Comment by zularizal** [comment]
What do you think about this color?

![bitmap](https://user-images.githubusercontent.com/38547278/57914106-3fba4b80-78b8-11e9-825c-b29e3ccb7c66.png)

**Comment by Ubpa** [comment]
the icon at row 2, column 1 is great 👍

here is my last request ヽ(￣▽￣)ﾉ
could you make the right shadow parallel to the left one?

you can open a pull request with your changes

[_]~(￣▽￣) cheers

**Comment by zularizal** [comment]
Hi @Ubpa , I sent a pull request. #2 

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1sho0i6KCR-NBjY84WW5gBULZKvpxMBEv
