### ISSUE TITLE
项目无法构建，找不到UGit仓库

### ISSUE THREAD

**Issue by jz0224** [Ubpa/RenderLab#4]
![微信截图_20200326180629](https://user-images.githubusercontent.com/30064494/77634825-9094d900-6f8c-11ea-9d2e-24805ef69772.png)
是不是您把UGit设为了私有库啊，麻烦看一下，多谢啦~

**Comment by Ubpa** [comment]
目前无法编译通过，本人正在重构框架，大概 2-3 周后搞定

**Comment by jz0224** [comment]
好的好的，期待~

**Comment by Ubpa** [comment]
由于新引擎还比较久远才能给出，已经将问题修复了，在 setup.md 中给出了解决方案
